---
title: "Organisation of folders and files"
subtitle: "The model parameter and code files"
author: "David O'Sullivan"
date: 19 February 2025
date-modified: 6 May 2026
lightbox: true
filters:
  - nutshell
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    code-fold: true
    html-math-method: katex
    embed-resources: true
knitr:
  opts_chunk:
    warning: false
    message: false
    # echo: false
    R.options:
      knitr.table.html.attr: "quarto-disable-processing=true"
---

The model folder contains quite a few subfolders. Key folders and their contents are listed in [this section](#representative-folder-listing) at the end of this document, and described in the sections below.

## Data
A key idea underpinning model development was to avoid hard coding dozens, or even hundreds of settings into the model code. To that end a `data` folder in the same directory as the model source code has subfolders `market` and `spatial` themselves with subfolders containing model input files that can specify scenarios in terms of the parameter settings (the `market` folder) and region or catchment where the model is to be run (the `spatial` folder).

### Market
Each `./data/market/<scenario-name>` subfolder contains a collection of files that configure aspects of the agricultural market, which together form a scenario. These are listed below under three different groupings of **Behavioural**, **Economic**, and **Environmental**, although note all files in a scenario are currently in the same folder. Also note that this subdivision is to keep things comprehensible and is not a firm classification of model elements into distinct subcategories.[^5]

[^5]: It may make sense at a later date to reorganise the model parameterisation files to make development of distinctly localised scenarios easier, and accompanying that change to introduce more consistent naming conventions or a folder structure on the files.

#### Behavioural

Filename `.csv`                 | Purpose
:-                              | :-----
`farmer-threshold-matrix`       | Baseline probabilities of adoption by farmers of available management interventions by land use and farmer disposition.
`farmer-dispositions`           | Farmer dispositions (e.g. `"pro_environmental"`) in the model along with their relative proportions.
`conversion-probabilities`      | Relative probability of conversion between the different land uses.

The first of these files (`farmer-threshold-matrix.csv`) effectively defines the available land use types and interventions and additional rows or columns could be added to it to further detail the model's sectoral representation. **Note:** Extending the model in this way to add interventions is trivial; adding additional land uses will require a small amount of additional code to deal with visualisation aspects.

#### Economic

Filename `.csv`                 | Purpose
:-                              | :-----
`costs`                         | Costs (per unit of output) by land use and land use capability class.
`prices`                        | Market price of commodities (per unit of output) by land use.
`yields`                        | Yields (in unit of output per hectare) by land use and land use capability class.
`costs-yields-time-series` and `prices-time-series` | Time series multipliers for costs, yields, and prices.
`suitabilities`                 | Binary 1/0 indicator of which land use are allowed on each land use capability class.
`intervention-details`          | _Impact of interventions_ on costs, yields, capital costs, and the various environmental metrics, by landuse; _initial proportion_ of holdings of each landuse on which intervention should be implemented at model initialisation; a _maximum proportion_ for each of these on each landuse type reflecting possible obstacles to implementation; and _nudge_ is any additional policy boost to adoption of each intervention by landuse.

#### Environmental

Filename `.csv`                 | Purpose
:-                              | :-----
`environmental-metrics`         | A list of environmental metrics which the modeller wishes to explore in this scenario. Each metric should have a name, and a limit and price associated (where either may be NA), which are regulatory limits and taxes associated with that metric. **This is where the carbon price in the model is set.** Files called `<factor>.csv` and corresponding rows in `intervention-details` must also be present for all listed metrics. Metrics can be 'commented out' by preceding them with a `#` in `environmental-metrics.csv`, when they will then have no impact on a model run.
`<factor>`                      | Where `<factor>` may be `costs`, `yields`, or any of the active _environmental-metrics_ listed in `environmental-metrics.csv`. Mean and st dev. of `<factor>` per ha. by land use and land use capability.

### Geographical setting
The geographical setting of the model is initialised from GIS files.[^1]

[^1]: A 'legacy' random initialisation option can be used by setting an internal global variable `geography-from-files?` to `false`, but is no longer available from the model GUI.

Initialisation from GIS files uses a `parcels.shp` shapefile, and `luc.asc` and `landuse.asc` raster files to specify respectively the farms, LUC landscape, and land use in the model. Farms are subdivided into holdings based on LUC. Different catchments can be applied by providing these files in a folder `./data/spatial/<region-name>`. Localisation of the model to a particular settings is relatively straightforward given appropriate files for a particular catchment. These files have attributes as follows:

+ `parcels.shp` should have a unique `STR_ID` attribute per farm. This must be a string _not_ a number (numbers are subject to interpolation when assigned to patches by the NetLogo GIS extension).
+ `luc.asc` should contain integer values from 1 to 8 inclusive and -9999 values outside the study area.
+ `landuse.asc` should contain integer values encoded as follows:

Value | Landuse
-:|:----
0     | Horticulture (referred to in model code as `"Crop"`)
1     | Dairy (`"Dairy"`)
2     | Forestry (`"Forest"`)
3     | Beef and lamb (`"SNB"`; includes also deer)
1000  | Not farmed, but inside the catchment (scrub, indigenous forest, conservation land)
-9999 | Outside the catchment

The important thing here is not the specific encoding chosen, but that any changes made here match an alphabetical ordering of the corresponding landuses in the `farmer-threshold-matrix.csv` file. At present these are `"Crop"`, `"Dairy"`, `"Forest"`, and `"SNB"` corresponding to 0, 1, 2, 3 above. If a more detailed landuse classification is desired then the new landuses would need to be added in all initialisation files.

::: {style="color:grey;"}
#### Random geography (LEGACY)
Random initialisation first sets up a land use capability (LUC) landscape using iterative smoothing[^3] (the number of iterations of smoothing is set by `luc-aggregation-steps`), then randomly distributes farmers across the landscape assigning them a farm based on Voronoi polygons[^4] and breaking the farm into sub-farm level holdings based on contiguous areas of the same LUC. Additionally a voter model is iteratively run on the landuses so that regions of uniform landuse are produced (the number of iterations of the voter model set by `landuse-aggregation-steps`).

[^3]: See pages 60-63 in O’Sullivan D and GLW Perry. 2013. _Spatial Simulation: Exploring Pattern and Process_. Chichester, UK: Wiley.
[^4]: Okabe A, B Boots, K Sugihara, and SN Chiu. 2000. _Spatial Tessellations: Concepts and Applications of Voronoi Diagrams_. 2nd edn. Chichester, UK: Wiley.
:::

## Code
To make managing model source code easier it is broken into a main `.nlogox`[^2] file and a number of NetLogo source `.nls` files. Unfortunately the built in IDE for NetLogo is limited, so this breakdown is not perfect, but it at least each file a manageable size (a few hundred lines at most), where a monolithic flat file would be an unwieldy 3200+ lines (and counting). The files are as follows:

[^2]: The `.nlogox` file format is new in the recently released (late 2025) version 7 of NetLogo. It is _not_ compatible with earlier versions of the platform.

Filename             | Purpose
:-                   |:----
`abm-working.nlogox` | Definition of globals, setup and main model loop, model reset code
`mtm-geography.nls`  | Setup of model geography, whether from GIS files or random
`mtm-read-files.nls` | Reading of market setting files into tables and matrices...
`mtm-tables.nls`     | ... using code in this file for reading tabular data in various formats
`mtm-farm.nls`       | Initialisation and maintenance of farm agents
`mtm-farmer.nls`     | Initialisation and maintenance of farmer agents, primarily procedures for choosing among options for land use change / management interventions
`mtm-holding.nls`    | Initialisation and maintenance of holding agents, primarily calculation of income and costs
`mtm-loans.nls`      | Code for calculation of loan payments, outstanding principal, etc.
`mtm-plots.nls`      | Plotting of some model statistics for interactive exploration
`mtm-results.nls`    | Recording and writing to files of model run results
`mtm-render.nls`     | Visual rendering of model state
`mtm-utils.nls`      | Various list, matrix, string, statistical distributions, and other utility functions, used throughout the model
`mtm-profile.nls`    | Profiling of model performance (not much used)

## Representative folder listing
Below is a compressed listing of required files and folders to run the model. Details of these have been described above.

```
├─ abm-working.nlogox
├─ mtm-farmer.nls
├─ ... ## more .nls code files as detailed above
├─ data
   ├─ market
   │  ├─ default
   │  │  ├─ farmer-threshold-matrix.csv
   │  │  ├─ farmer-dispositions.csv
   │  │  ├─ conversion-probabilities.csv
   │  │  ├─ costs.csv
   │  │  ├─ prices.csv
   │  │  ├─ yields.csv
   │  │  ├─ costs-yields-time-series.csv
   │  │  ├─ prices-time-series.csv
   │  │  ├─ suitabilities.csv
   │  │  ├─ intervention-details.csv
   │  │  ├─ environmental-metrics.csv
   │  │  ├─ ghg_emissions.csv
   │  │  └─ ... ## More .csv named metric files
   │  └─ ... ## More named scenario folders
   ├─ output
   │  └─ scratch         ## Folder for results
   │     ├─ results-< DATE TIME >-header.csv
   │     └─ results-< DATE TIME >.csv
   └─ spatial
      ├─ Oreti
      │  ├─ landuse.asc  ## These spatial data files
      │  ├─ luc.asc      ## consist of several files
      │  └─ parcels.shp  ## with shared basenames
      └─ ... ## More named region folders
```

::: {.callout-note collapse="true"}
#### Update History

| Date       | Changes
|:-          |:------
| 2025-02-19 | Initial post.
| 2025-08-05 | Split out to a separate model file config page.
| 2025-10-17 | Updated to reflect addition of debt.
| 2026-05-04 | Updated reflecting change of random initialisation to hard-coded option only.
| 2026-05-06 | Partitioned market file table into behavioural, economic, and environmental. Reordered to put data folders first (likely of more interest).

:::

