---
title: "Debt calculations"
subtitle: "Farmer indebtedness is central to their decision making"
author: "David O'Sullivan"
date: 5 May 2026
lightbox: true
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    code-fold: true
    html-math-method: katex
    embed-resources: true
knitr:
  opts_chunk:
    warning: false
    message: false
    # echo: false
    R.options:
      knitr.table.html.attr: "quarto-disable-processing=true"
---

```{r echo=FALSE,warnings=FALSE,results=FALSE,message=FALSE}
#| label: libraries
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
```

## Parameters controlling debt
The model parameters affecting debt are `interest-rate` and `mortgage-term`. These are annualised rates, although calculations are carried out with respect to the 5 year model time step.

The farmer parameters associated with debt are `loan-principal`, `loan-rate`, `current-debt`, `debt-payments`, `debt-maturity`, and `debt-free?`. Together these allow calculation of the `dsr` (debt service ratio) parameter.

## Basic debt calculations
The equations governing loan-related calculations are as follows. The annual repayment $X$, on a loan of principal amount $P$, term $T$ years, at interest rate $r$ (expressed as a fraction), is given by

$$
X = Pr\frac{R^T}{R^T-1}
$$ {#eq-repayments}

where $R=1+r$.

The outstanding debt $D$, on a loan of principal amount $P$, term $T$, at interest rate $r$, after $N$ years is given by

$$
D = P\left[R^N-\frac{R^T(R^N-1)}{R^T-1}\right]
$$ {#eq-outstanding-debt}

All amounts determined in the model are annual amounts, so, for example `current-income` is the income in the current year, not aggregate income over the five-year period which the current model tick represents.

This means we can calculate debt repayments as an annual amount (based on eqn.[-@eq-repayments] above) and simply deduct this from the profit determined as described in the [income and costs page](06-holding-income-and-costs.qmd). Outstanding debt to pay is always determined from eqn.[-@eq-outstanding-debt] not by accumulating repayments over time, thus avoiding issues that might arise due to floating point calculations leaving small amounts owing or overpaid. Instead a farmer's `debt-maturity` parameter is incremented by 5 years each model tick, and eqn.[-@eq-outstanding-debt] is used to determine the current amount still owing. When `debt-maturity` exceeds the `mortgage-term` it is assumed that all debt has been paid and the `debt-free?` flag is set `true`.

## Debt, income, and costs
If debt repayments exceed current profit, then the loan is refinanced by adding the deficit to the current outstanding debt calculated from eqn.[-@eq-outstanding-debt]. Similarly, when a management intervention is undertaken the associated capital cost (found in the `intervention-details.csv` file) is added to the current outstanding debt, and refinanced at the current interest rate with the same end date as the existing loan.

If current profit exceeds debt repayments, then net 'final' profit is set to the current profit minus the debt repayments.

## Debt service ratio (DSR)
A farmer's debt service ratio is the ratio of debt repayments to the estimated value of the farm.

### Estimated value
The farm's estimated value is based on current profit (before debt repayments), and is a simple multiplier based on the reciprocal of a hard-coded _discount rate_, currently set to 8% so that farm's are valued at 12.5 times their current profit. Discount rate could be made a variable model parameter if this is deemed useful.

::: {.callout-note collapse="true"}
#### Update History

| Date | Changes
|:-|:------
| 2026-05-05 | Initial post.

:::
